baseURL = 'https://nsochoaga.github.io/'
languageCode = 'en-us'
title = 'Nicholson Ochoa - Portafolio'
theme = "hugo-book"

# Book configuration
disablePathToLower = true
enableGitInfo = true

[params]
BookTheme = 'dark'